schedules:
  commit:
    # Run short suite on commit with enough C* versions to get full protocol version coverage.
    schedule: per_commit
    env_vars: |
      TEST_GROUP="long"
    disable_commit_status: true
    disable_pull_requests: true
    notify:
      slack: java-driver-dev-bots
java:
  - oraclejdk9
  - oraclejdk10
os:
  - ubuntu/trusty64/m3.large
cassandra:
  - '1.2'
  - '2.0'
  - '2.1'
  - '2.2'
  - '3.0'
  - '3.11'
build:
  - script: |
      . /usr/local/bin/jdk_switcher.sh
      jdk_switcher use oraclejdk8
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.2.5
      export PATH=$MAVEN_HOME/bin:$PATH
      mvn -B -V install -DskipTests
  - script: |
      . /usr/local/bin/jdk_switcher.sh
      jdk_switcher use $JAVA_VERSION
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -P$TEST_GROUP
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Pisolated
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
